# This is my first attempt at writing a GitHub CI YAML file. Let's see how it goes.

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # GitHub says: "Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it"
    - uses: actions/checkout@v2
    
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'

    - name: Install requirements
      run: |
        cd ${GITHUB_WORKSPACE}
        python -m venv venv
        . venv/bin/activate
        make install-tests

    - name: Run a multi-line script
      run: |
        cd ${GITHUB_WORKSPACE}
        . venv/bin/activate
        make tests
